#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer DisplacementsAndNormalsOut { vec4 displacementsAndNormals[]; };
layout(set = 0, binding = 1) buffer Scale { float scale; };

#include "constants.glsl"

void main() {
  uint x = gl_GlobalInvocationID.x;
  uint y = gl_GlobalInvocationID.y;
  uint idx = y * tileSize + x;
  displacementsAndNormals[idx].y *= scale;
}
