#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform PushConstants {
  int rb;
  float cellSize;
  float dt;
} pc;

#include "common.glsl"

void main() {
  float dtRhoSize = (density * pc.cellSize / pc.dt);

  int x = int(gl_GlobalInvocationID.x);
  int y = int(gl_GlobalInvocationID.y);

  if (isSolid(x, y)) {
    setDiv(x, y, 0.0);
    return;
  }

  float div = getVel(x + 1, y).x - getVel(x, y).x + getVel(x, y + 1).y - getVel(x, y).y;
  setDiv(x, y, div * dtRhoSize);
}
