#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(push_constant) uniform PushConstants {
  int rb;
  float cellSize;
  float dt;
  ivec3 cellCount;
} pc;

#include "common.glsl"

void main() {
  ivec3 p = ivec3(gl_GlobalInvocationID);
  if (p.x >= pc.cellCount.x || p.y >= pc.cellCount.y || p.z >= pc.cellCount.z)
    return;

  float dtRhoSize = (density * pc.cellSize / pc.dt);

  if (isSolid(p, pc.cellCount)) {
    setDiv(p, pc.cellCount, 0.0);
    return;
  }

  float div = getVel(p + ivec3(1, 0, 0), pc.cellCount).x - getVel(p, pc.cellCount).x +
              getVel(p + ivec3(0, 1, 0), pc.cellCount).y - getVel(p, pc.cellCount).y +
              getVel(p + ivec3(0, 0, 1), pc.cellCount).z - getVel(p, pc.cellCount).z;
  setDiv(p, pc.cellCount, div * dtRhoSize);
}
